### ISSUE TITLE
Multi GPU trouble

### ISSUE THREAD

**Issue by fantrapa** [ilkerccom/bitcrackrandomiser#24]
Hello. When start multiGPU see this:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BitcrackRandomiser.Program.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String TargetAddress, List`1 ProofValues, String HEX, Settings settings, Process process, Int32 GPUIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Program.cs:line 0
   at BitcrackRandomiser.Program.<>c__DisplayClass5_0.<RunBitcrack>b__0(Object o, DataReceivedEventArgs s) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Program.cs:line 204
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by ilkerccom** [comment]
App updated for multi gpu problems.
