### ISSUE TITLE
Issue running on vast.ai

### ISSUE THREAD

**Issue by cujo30227** [ilkerccom/bitcrackrandomiser#27]
Hi,
I followed all steps to install this repository on an NVIDIA instance on vast.ai. However, when executing `dotnet run`, I get the following error. Any advise on what to do? I'm logged in through SSH as root.

```
Unhandled exception. System.AggregateException: One or more errors occurred. (An error occurred trying to start process '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/bin/Debug/net6.0/bitcrack/./cuBitcrack' with working directory '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser'. Permission denied)
 ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/bin/Debug/net6.0/bitcrack/./cuBitcrack' with working directory '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at BitcrackRandomiser.Randomiser.Scan(Settings settings, Int32 gpuIndex) in /root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 192
   at BitcrackRandomiser.Program.<>c__DisplayClass1_0.<Main>b__1(Int32 i) in /root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/Program.cs:line 45
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at BitcrackRandomiser.Program.Main(String[] args) in /root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/Program.cs:line 43
```

**Comment by ilkerccom** [comment]
Make sure you follow all the steps completely. The best way is to use a docker image. You can also create your own docker image using [dockerfile](https://github.com/ilkerccom/bitcrackrandomiser/blob/main/Docker/Dockerfile) on Github.

**Comment by ilkerccom** [comment]
I am closing the issue, please reply if it is not resolved and still persists.
