### ISSUE TITLE
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')

### ISSUE THREAD

**Issue by taj1989** [ilkerccom/bitcrackrandomiser#33]
Running using clBitcrack
app_path=clBitcrack
app_arguments=-b 64 -t 256 -p 256

After a few seconds I get this error:
GeForce GT 525M  384 / 1024MB | 5 targets 6.10 MKey/s (62,914,560 total) [00:00:08] [GPU=0] [HEX=3F94A08]               System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Helper.cs:line 112
   at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Flagger.cs:line 25
   at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 230
   at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 257
   at BitcrackRandomiser.Randomiser.<>c__DisplayClass7_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 179
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by ilkerccom** [comment]
Hello, have you tested Bitcrack externally? The card is very old, Bitcrack's OpenCL version has some bugs. Can you provide information by doing an external test (without using bitcrackrandomiser)

Thanks.

**Comment by taj1989** [comment]
Hi, just gave it a try, seems that clBitcrack works in stand-alone:

\bitcrackrandomiser\bitcrack>clBitcrack.exe 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so -b 64 -t 256 -p 256
[2024-03-06.13:17:38] [Info] Compression: compressed
[2024-03-06.13:17:38] [Info] Starting at: 0000000000000000000000000000000000000000000000000000000000000001
[2024-03-06.13:17:38] [Info] Ending at:   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
[2024-03-06.13:17:38] [Info] Counting by: 0000000000000000000000000000000000000000000000000000000000000001
[2024-03-06.13:17:38] [Info] Compiling OpenCL kernels...
[2024-03-06.13:17:38] [Info] Initializing GeForce GT 525M
[2024-03-06.13:17:39] [Info] Generating 4,194,304 starting points (160.0MB)
[2024-03-06.13:17:45] [Info] 10.0%
[2024-03-06.13:17:47] [Info] 20.0%
[2024-03-06.13:17:49] [Info] 30.0%
[2024-03-06.13:17:51] [Info] 40.0%
[2024-03-06.13:17:53] [Info] 50.0%
[2024-03-06.13:17:55] [Info] 60.0%
[2024-03-06.13:17:57] [Info] 70.0%
[2024-03-06.13:17:59] [Info] 80.0%
[2024-03-06.13:18:01] [Info] 90.0%
[2024-03-06.13:18:03] [Info] 100.0%
[2024-03-06.13:18:03] [Info] Done
GeForce GT 525M  384 / 1024MB | 1 target 6.20 MKey/s (767,557,632 total) [00:02:02]

**Comment by ilkerccom** [comment]
Can you share the settings.txt file? (Removing private data)

**Comment by taj1989** [comment]
// Select puzzle number [66,67,68] or [38] for test pool
target_puzzle=66

// which app will be used [bitcrack]
app_type=bitcrack

// App folder path [cuBitcrack, clBitcrack or full path of the Bitcrack app]
app_path=clBitcrack

// App arguments
// Example for bitcrack: -b 896 -t 256 -p 256
app_arguments=-b 64 -t 256 -p 256

// User token value. You can create it by logging into your account at btcpuzzle.info
user_token={removed}

// Wallet address for worker. {wallet}.{worker}. If no worker name it will create random.
wallet_address={removed}

// Enter your GPU Count [1-16]
gpu_count=1

// Use only one GPU at index. [0-15]
gpu_index=0

// Scan type [default,includeDefeatedRanges,excludeIterated{2/3/4},excludeContains{3/4},excludeStartsWith{XXX}]
scan_type=default

// Scan for rewards of the pool [true,false]
scan_rewards=false

// Custom range to scan Example; [2D,3BA,3F12,2881A or none]
custom_range=none

// Share progress with your API [https://yourwebsite/example.php]
api_share=none

// Send notifications to Telegram
telegram_share=false

// Telegram access token
telegram_accesstoken=0

// Telegram chat id
telegram_chatid=0

// Send notification when eack key scanned
telegram_share_eachkey=false

// If true and the private key found; private key will be send to Telegram 
untrusted_computer=false

// Run app in test mode. Example private key will be found
test_mode=false

// Force continue if key found
force_continue=false

// Private pool id
private_pool=none

**Comment by ilkerccom** [comment]
Can you test like below and verify it works?
```bash
$ clBitcrack.exe -b 64 -t 256 -p 256 -d 0 --keyspace 3F94A080000000000:3F94A090000000000 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so 1AYRwmDyowDQLZKhzHmtGNwsD7bUp1qq9A 15JVX6DrCLc1JeFFLu5TmEFNYwz7e2JiBp 16otECJAsiiM54WyX98kkrmDNTEaSzi6fS 
```

If it works smoothly, I need to investigate the error in the application codes. Thank you for feedback.

**Comment by taj1989** [comment]
\bitcrackrandomiser\bitcrack>clBitcrack.exe -b 64 -t 256 -p 256 -d 0 --keyspace 3F94A080000000000:3F94A090000000000 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so 1AYRwmDyowDQLZKhzHmtGNwsD7bUp1qq9A 15JVX6DrCLc1JeFFLu5TmEFNYwz7e2JiBp 16otECJAsiiM54WyX98kkrmDNTEaSzi6fS
[2024-03-06.13:52:38] [Info] Compression: compressed
[2024-03-06.13:52:38] [Info] Starting at: 000000000000000000000000000000000000000000000003F94A080000000000
[2024-03-06.13:52:38] [Info] Ending at:   000000000000000000000000000000000000000000000003F94A090000000000
[2024-03-06.13:52:38] [Info] Counting by: 0000000000000000000000000000000000000000000000000000000000000001
[2024-03-06.13:52:38] [Info] Compiling OpenCL kernels...
[2024-03-06.13:52:38] [Info] Initializing GeForce GT 525M
[2024-03-06.13:52:39] [Info] Generating 4,194,304 starting points (160.0MB)
[2024-03-06.13:52:45] [Info] 10.0%
[2024-03-06.13:52:48] [Info] 20.0%
[2024-03-06.13:52:53] [Info] 30.0%
[2024-03-06.13:52:55] [Info] 40.0%
[2024-03-06.13:52:57] [Info] 50.0%
[2024-03-06.13:52:59] [Info] 60.0%
[2024-03-06.13:53:01] [Info] 70.0%
[2024-03-06.13:53:03] [Info] 80.0%
[2024-03-06.13:53:05] [Info] 90.0%
[2024-03-06.13:53:07] [Info] 100.0%
[2024-03-06.13:53:07] [Info] Done
GeForce GT 525M  384 / 1024MB | 4 targets 6.15 MKey/s (62,914,560 total) [00:00:08][2024-03-06.13:53:17] [Info] Reached end of keyspace

**Comment by ilkerccom** [comment]
I haven't found a working version yet. I'm closing the issue, I'll research it again when I have free time.
