### ISSUE TITLE
error when running on an amd pc

### ISSUE THREAD

**Issue by goatshags** [ilkerccom/bitcrackrandomiser#45]
Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Helper.cs:line 168
   at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Flagger.cs:line 25
   at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 272
   at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 301
   at BitcrackRandomiser.Randomiser.<>c__DisplayClass8_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 209
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by masikrus** [comment]
@goatshags just update you dotnet sdk https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by ilkerccom** [comment]
Use Bitcrack v0.30 for AMD gpus. Vanitysearch doesnt support AMD, cuda only.

**Comment by Julienbxl** [comment]
![bitcrack](https://github.com/user-attachments/assets/759a9ab9-ddf8-401c-8836-facf422a3c56)

Got same problem donet is last version, and in settings it is configured to use bitcrack and not vanitysearch

**Comment by FachruRozi77** [comment]
i've got the same problem. latest 6.0 SDK and bitcrack version 0.30.

**Comment by thewhitegrizzli** [comment]
why do you even bother running any of these tools other than on 1,0000000
billion Google Cloud 224vcpu instances
you will not crakc anything, do you understand that?
Laurent

**Comment by thewhitegrizzli** [comment]
like JEsus.
Laurent

**Comment by luongthomas** [comment]
Running into the same issue when both running vanitysearch and bitcrack.

Using GTX 3080

```
[2024-08-25-21:53:42] [Info] Scan completed.                                                                                    Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Helpers/Helper.cs:line 168
   at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Helpers/Flagger.cs:line 25
   at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 272
   at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 301
   at BitcrackRandomiser.Randomiser.<>c__DisplayClass8_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 209
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted
```

**Comment by ilkerccom** [comment]
> ![bitcrack](https://private-user-images.githubusercontent.com/116493163/354100903-759a9ab9-ddf8-401c-8836-facf422a3c56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2ODIxMTQsIm5iZiI6MTcyODY4MTgxNCwicGF0aCI6Ii8xMTY0OTMxNjMvMzU0MTAwOTAzLTc1OWE5YWI5LWRkZjgtNDAxYy04ODM2LWZhY2Y0MjJhM2M1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQyMTIzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQ1NzQ5MTE4MjdjZWIyMDU2ZmQzZWY4NWFmNjE5ZWNmN2NiMTVhMGUzMWRhNDI0ZGM2OWUwMDRmZmNlNTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QfE9CibuuqyyKoEWJCh8rTLui5CUq4nmwqqq1bg0hc)
> 
> Got same problem donet is last version, and in settings it is configured to use bitcrack and not vanitysearch

Using AMD or NVidia?

> i've got the same problem. latest 6.0 SDK and bitcrack version 0.30. the problem is the same as above. string s.

The problem seems to be related to AMD and OpenCL. I will do a test on AMD based systems soon. I will give information about the subject.

> Running into the same issue when both running vanitysearch and bitcrack.
> 
> Using GTX 3080 and latest dotnet 6.0 SDK
> 
> ```
> [2024-08-25-21:53:42] [Info] Scan completed.                                                                                    Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
>    at System.Text.Encoding.GetBytes(String s)
>    at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Helpers/Helper.cs:line 168
>    at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Helpers/Flagger.cs:line 25
>    at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 272
>    at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 301
>    at BitcrackRandomiser.Randomiser.<>c__DisplayClass8_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 209
>    at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
>    at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
> --- End of stack trace from previous location ---
>    at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
>    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>    at System.Threading.Thread.StartCallback()
> Aborted
> ```

This problem usually occurs when it cannot find the "proof of work" addresses. Is the problem resolved or is it still ongoing?
