### ISSUE TITLE
Error when running BitcrackRandomiser.dll

### ISSUE THREAD

**Issue by luongthomas** [ilkerccom/bitcrackrandomiser#51]
```
==========
[2024-08-25-02:33:39] [Info] [v1.3.1.1] [bitcrack] starting... Puzzle: [66]
[2024-08-25-02:33:39] [Info] Target address: 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so
[2024-08-25-02:33:39] [Info] Test mode is passive.
[2024-08-25-02:33:39] [Info] Scan type(s): [1] scan type(s) have been set.
[2024-08-25-02:33:39] [Info] API share: False / Telegram share: False
[2024-08-25-02:33:39] [Info] Untrusted computer: False
[2024-08-25-02:33:39] [Info] Progress: Visit the [btcpuzzle.info] for statistics.
[2024-08-25-02:33:39] [Info] Worker name: bc1ql47paedsm2alslh3v5qmfll2cpp7xca75wzxjr.worker4052
--------------------------------------------------------------------------------------------------------------------------------
Unhandled exception. System.AggregateException: One or more errors occurred. (An error occurred trying to start process '/app/bitcrackrandomiser/bitcrack/./cuBitcrack' with working directory '/app/bitcrackrandomiser'. Permission denied)
 ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/app/bitcrackrandomiser/bitcrack/./cuBitcrack' with working directory '/app/bitcrackrandomiser'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at BitcrackRandomiser.Randomiser.Scan(Settings settings, Int32 gpuIndex) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 234
   at BitcrackRandomiser.Program.<>c__DisplayClass2_0.<Main>b__3(Int32 i) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Program.cs:line 66
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at BitcrackRandomiser.Program.Main(String[] args) in /app/cloned/bitcrackrandomiser/BitcrackRandomiser/Program.cs:line 62
Aborted
```

**Comment by ilkerccom** [comment]
Hello, the problem seems to be related to permissions. Can you try with "sudo"?
