### ISSUE TITLE
Error: AMD, clBitcrack issue

### ISSUE THREAD

**Issue by SirCringineer** [ilkerccom/bitcrackrandomiser#52]
Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
                      (This line got overwritten)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at BitcrackRandomiser.Helpers.Helper.SHA256Hash(String data) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Helper.cs:line 126
   at BitcrackRandomiser.Helpers.Flagger.Flag(Settings settings, String hex, Int32 gpuIndex, String proofKey, String gpuName) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Helpers\Flagger.cs:line 25
   at BitcrackRandomiser.Randomiser.JobFinished(String targetAddress, String hex, Settings settings, Boolean keyFound, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 262
   at BitcrackRandomiser.Randomiser.OutputReceivedHandler(Object o, DataReceivedEventArgs e, String targetAddress, List`1 proofValues, String hex, Settings settings, Process process, Int32 gpuIndex) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 285
   at BitcrackRandomiser.Randomiser.<>c__DisplayClass7_0.<Scan>b__0(Object o, DataReceivedEventArgs s) in C:\Users\ilker\source\repos\bitcrackrandomiser\BitcrackRandomiser\Randomiser.cs:line 211
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

I have upgraded/downgraded software, tried different settings, and did as much troubleshooting I can to my knowledge. I am using bitcrack v0.30 and have the lastest version of dotnet. The issue persists

**Comment by ilkerccom** [comment]
Hello, 

Yes AMD and clBitcrack have problems. I have not an AMD gpu and i can't test it.

I will try to solve the problem by renting a graphics card soon. If I can solve the problem, I will inform you.

Thanks.
